### ISSUE TITLE
SecLists big.txt compatability issue?

### ISSUE THREAD

**Issue by AWildBeard** [PinkP4nther/EroDir#2]
I was using EroDir yesterday with [SecLists Web Content Discovery list big.txt](https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/big.txt) and I kept getting an error that said there was an invalid line in the file. This error would occur almost immediately on program run. I have done absolutely zero to narrow down the issue (I just moved on to a different list) but I figured I should report this issue before trying to figure out which line in the ~20,000 line file was causing the issue.

**Comment by PinkP4nther** [comment]
Hey Beard :D I did some debugging on this issue! This is caused by invalid UTF-8 characters being read. This is because the big.txt file encoding is ISO-8859 to fix this just convert big.txt to UTF-8.

$ iconv -f ISO-8859-1 -t UTF-8 big.txt > big1.txt

**Comment by PinkP4nther** [comment]
The exact line causing the issue you can find with a sed command "sed '16072q;d' /opt/SecLists/Discovery/Web-Content/big.txt" this will print out the 16,072 line of big.txt which has a non UTF-8 character. The character is an o with an accent mark from ISO-8859-1 encoding. The character number is 243 for this specific encoding which is out of range of UTF-8.

**Comment by PinkP4nther** [comment]
Added verbose for when this error happens, also will skip the invalid UTF-8 line for now, until I find the best solution for safely using more encodings like Latin-1
